FROM rccv-image:latest

RUN printf "\n\
    export imp=Dockerfile_imp\n\
    alias rebuild='rm -r ../build/* && cmake .. && make && cls \ 
    && ./visitor-multi-threading' \n\
    " >> /root/.bashrc
CMD [ "/bin/bash" ]